### ISSUE TITLE
Add petition text. 

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Begrotingstekort-Petitie#15]
Code it into the platform -> @tjoosten
Write the petition text -> @alfamongrel

**Comment by Tjoosten** [comment]
@alfamongrel Update needed.

**Comment by alfamongrel** [comment]
Aangezien onze regering het geld blijft halen bij de kleine man en toch nog steeds te kort komt.
Hebben wij besloten om de regering even te helpen.
Met deze speciale petitie proberen wij duidelijk te maken dat er andere manieren zijn.
Wij burgers doen het zelf, voel u  vrij om de regering een handje toe te steken !
